Add new caching, fixes to APIs chapter, python3
presnick/ProgramsInformationPeople pull request #177
Opened 2017-06-29 21:59 UTC by aerenchyma

Here are my proposed changes for caching REST APIs.

When I build and test this, it looks fine, but there's one problem: the forward/back arrows don't follow what the index says (and don't take my new Functions with REST APIs chapter into account). Any thoughts on that?

Can talk more about what my thought process is adding this, can edit for feedback, etc. Most of this is a clarified, shortened version of what worked well in lecture. 

I'd like to put this online on the publicpy3 version of the book to release it to 506 and 507 students or resolve it so we can.

2017-06-29 22:00 UTC, aerenchyma commented
There are also .rst fixes and cleanup on the publicpy3 branch to make, but I have (as you can see here) not yet changed those. I'll go through on a full cleanup run for those and other things soon.

2017-06-30 19:52 UTC, presnick requested changes

2017-06-30 19:52 UTC, presnick commented on _sources/UsingRESTAPIs/cachingResponses.rst
> +1. Before doing some expensive operation (like calling ``requests.get`` to get data from a REST API), check whether you have already saved contains the results that would be generated by making that
I think you can just delete the word "contains" here.

2017-06-30 19:52 UTC, presnick commented on _sources/UsingRESTAPIs/cachingResponses.rst
> +3. If not, perform the expensive operation and save the results (e.g. the complicated data) in your cache so you won't have to perform it again the next time.
Are you trying to delay introducing the word "cache". If so, then it can't be used here. If not, then why not use it in #1?

2017-06-30 19:52 UTC, presnick commented on _sources/UsingRESTAPIs/cachingResponses.rst
> +As an extra challenge, it's also worth noting that even supposing the exact same caching structure and setup, there are a number of different versions of that ``get_from_datamuse_caching`` function y
I suspect that students won't understand what you're getting at with this challenge. Can you give some hints.

2017-06-30 19:52 UTC, presnick commented on _sources/UsingRESTAPIs/flickr.rst
> -    def canonical_order(d):
Why did you remove the caching from here? Is it before caching gets introduced? If it's after, why not keep using caching, to reinforce it?

2017-06-30 19:54 UTC, aerenchyma commented on _sources/UsingRESTAPIs/cachingResponses.rst
> +1. Before doing some expensive operation (like calling ``requests.get`` to get data from a REST API), check whether you have already saved contains the results that would be generated by making that
I'll do that.

2017-06-30 19:55 UTC, aerenchyma commented on _sources/UsingRESTAPIs/cachingResponses.rst
> +3. If not, perform the expensive operation and save the results (e.g. the complicated data) in your cache so you won't have to perform it again the next time.
Not really, but trying to provide a lay-terms explanation of the whole process before introducing the idea that this thing they already understand is what "caching" is, that the saved info is the "cache". 

I'll try another way, or include the word along with the explanation.

2017-06-30 19:55 UTC, aerenchyma commented on _sources/UsingRESTAPIs/cachingResponses.rst
> +As an extra challenge, it's also worth noting that even supposing the exact same caching structure and setup, there are a number of different versions of that ``get_from_datamuse_caching`` function y
Definitely.

2017-06-30 19:59 UTC, aerenchyma commented on _sources/UsingRESTAPIs/flickr.rst
> -    def canonical_order(d):
Yes, this is now before caching gets introduced. The book before had flickr code with caching, but introduced the flickr API and caching together. I think it should be changed to first introduce the Flickr API, a more complex API than the previous subchapters have discussed, and then introduce a caching pattern.

I haven't included a function that both uses a caching pattern and gets data from the Flickr API, but that is partially motivated by the fact that doing so is in the problem set I plan to give, once students have written 
* a function that gets data from Flickr
and
* a function that caches data from a simpler API
in earlier psets/class sessions. But I'm not bothered by having it repeated in the textbook and a problem set, if you think it's a better idea.

2017-07-03 14:42 UTC, aerenchyma commented on _sources/UsingRESTAPIs/cachingResponses.rst
> +As an extra challenge, it's also worth noting that even supposing the exact same caching structure and setup, there are a number of different versions of that ``get_from_datamuse_caching`` function y
I decided here to give another example I think they'll often see e.g. in course materials that might be clearer for them, and leave a larger discussion of how to structure code for elsewhere; I thought hints might also be too hard.

If you think I should take this out and move it all to another chapter (the idea of differently structured code), I will; that's something I'd like to do long term, now I'm thinking about it, but I also want to make sure people have some of this idea in the textbook this week if possible.

2017-07-03 14:44 UTC, aerenchyma commented
I've added commits to this PR to address the comments above; of course let me know about additional concerns.

2017-07-03 15:00 UTC, presnick commented on _sources/UsingRESTAPIs/flickr.rst
> -    def canonical_order(d):
Good.

2017-07-03 15:06 UTC, presnick commented on _sources/UsingRESTAPIs/cachingResponses.rst
> +As an extra challenge, it's also worth noting that even supposing the exact same caching structure and setup, there are a number of different versions of that ``get_from_datamuse_caching`` function y
I'll accept this as is, but I think it really doesn't make sense as written. Do you want them to change the keys that are used for doing lookups in the cache? Or do you really mean that the cache file will be exactly the same and they are just rewriting some of the code? Part of the idea of modularity is that they should be able to change the internals (not just the code but also the structure of the file) as long as they keep the inputs and outputs the same.

2017-07-03 15:07 UTC, merged

2017-07-03 15:21 UTC, aerenchyma commented on _sources/UsingRESTAPIs/cachingResponses.rst
> +As an extra challenge, it's also worth noting that even supposing the exact same caching structure and setup, there are a number of different versions of that ``get_from_datamuse_caching`` function y
Well, there are a number of things. I'll make another PR and remove this, if this is ending up confusing.

My idea is that the structure of writing a function that caches data might have a couple different structures depending upon the goal of the function. I find that sometimes students want to complete something in their code that they're totally capable of, but their problem figuring it out comes from having solutions for problems that are too 'calcified' in one particular structure. 

But thinking about this more, that concept belongs separate from this chapter entirely, and perhaps there should be a chapter about modularity.